/**********************************************************************************
  Autogenerated by DaddaMatrix (generator.py) on 2024-04-15T04:30:28.339055-05:00
**********************************************************************************/
module dadda_multiplier (
  input  wire [7:0] a,
  input  wire [7:0] b,
  output wire [15:0] product
);

  wire   c5b87c13_749f_4d1b_8646_4ab3378e8a5a;
  assign c5b87c13_749f_4d1b_8646_4ab3378e8a5a = a[0] & b[0];
  wire   f95f8062_3816_42ce_9a01_453aa82aa344;
  assign f95f8062_3816_42ce_9a01_453aa82aa344 = a[0] & b[1];
  wire   v_3eef52ac_6195_4627_96b5_507e1b86bf39;
  assign v_3eef52ac_6195_4627_96b5_507e1b86bf39 = a[0] & b[2];
  wire   cba0d86c_fd35_439e_ad86_15b52ad7b774;
  assign cba0d86c_fd35_439e_ad86_15b52ad7b774 = a[0] & b[3];
  wire   v_348f0a68_d598_46cc_86ac_cf3917220f9c;
  assign v_348f0a68_d598_46cc_86ac_cf3917220f9c = a[0] & b[4];
  wire   v_2fe938e1_c440_40ee_956d_e2cf08b43207;
  assign v_2fe938e1_c440_40ee_956d_e2cf08b43207 = a[0] & b[5];
  wire   v_6e8bd969_5a8c_4cfb_b27f_bc219fc2b830;
  assign v_6e8bd969_5a8c_4cfb_b27f_bc219fc2b830 = a[0] & b[6];
  wire   v_789d6bce_b7aa_43ae_b7b8_fbb08e0b9a35;
  assign v_789d6bce_b7aa_43ae_b7b8_fbb08e0b9a35 = a[0] & b[7];
  wire   c8e02cbd_eca3_4c29_860b_7e21223bbb82;
  assign c8e02cbd_eca3_4c29_860b_7e21223bbb82 = a[1] & b[0];
  wire   v_938c4adf_0c3c_47f3_909d_1735d843f860;
  assign v_938c4adf_0c3c_47f3_909d_1735d843f860 = a[1] & b[1];
  wire   fb76f062_83f0_48a9_8b48_c1ebd32e8c32;
  assign fb76f062_83f0_48a9_8b48_c1ebd32e8c32 = a[1] & b[2];
  wire   v_61208a32_2b3a_47a2_a8e4_63e32df27f2e;
  assign v_61208a32_2b3a_47a2_a8e4_63e32df27f2e = a[1] & b[3];
  wire   d0d5447b_4d96_4162_8631_3197aee6fbe5;
  assign d0d5447b_4d96_4162_8631_3197aee6fbe5 = a[1] & b[4];
  wire   v_1d2ce400_bee3_4bcf_ad94_392b55ae8828;
  assign v_1d2ce400_bee3_4bcf_ad94_392b55ae8828 = a[1] & b[5];
  wire   e3eceaf8_b4db_4924_b72f_73344f9788f2;
  assign e3eceaf8_b4db_4924_b72f_73344f9788f2 = a[1] & b[6];
  wire   v_100c1758_140a_4142_9a4d_4fed30a453c6;
  assign v_100c1758_140a_4142_9a4d_4fed30a453c6 = a[1] & b[7];
  wire   v_259bb6be_d84f_49d7_87e9_795706241c88;
  assign v_259bb6be_d84f_49d7_87e9_795706241c88 = a[2] & b[0];
  wire   v_568c08f8_3850_4cf1_81aa_8ad0e5e8a283;
  assign v_568c08f8_3850_4cf1_81aa_8ad0e5e8a283 = a[2] & b[1];
  wire   a62a3e4b_a0aa_45f3_8cf0_ac8d7d8e2177;
  assign a62a3e4b_a0aa_45f3_8cf0_ac8d7d8e2177 = a[2] & b[2];
  wire   v_53863f08_0fcf_4548_bea8_65d01281c248;
  assign v_53863f08_0fcf_4548_bea8_65d01281c248 = a[2] & b[3];
  wire   fef89f08_5c22_497d_b9e9_75612421a902;
  assign fef89f08_5c22_497d_b9e9_75612421a902 = a[2] & b[4];
  wire   v_4e4a185f_ac21_47d0_b0b5_94dea7bf9f3e;
  assign v_4e4a185f_ac21_47d0_b0b5_94dea7bf9f3e = a[2] & b[5];
  wire   f4fcffeb_a640_44c2_b3a1_45f75bc65452;
  assign f4fcffeb_a640_44c2_b3a1_45f75bc65452 = a[2] & b[6];
  wire   v_8c4302bb_a1c1_446c_82b6_f699d6d7184f;
  assign v_8c4302bb_a1c1_446c_82b6_f699d6d7184f = a[2] & b[7];
  wire   a61f7549_5f9b_4cca_81f1_9dfeffa545cd;
  assign a61f7549_5f9b_4cca_81f1_9dfeffa545cd = a[3] & b[0];
  wire   df8d13ca_4a65_43f9_96d9_ac6de1c0e237;
  assign df8d13ca_4a65_43f9_96d9_ac6de1c0e237 = a[3] & b[1];
  wire   d3f8aa95_a395_4d1a_a4f7_6f39ea2b077b;
  assign d3f8aa95_a395_4d1a_a4f7_6f39ea2b077b = a[3] & b[2];
  wire   v_1b137b5f_c38c_471e_b330_09c52f7d7481;
  assign v_1b137b5f_c38c_471e_b330_09c52f7d7481 = a[3] & b[3];
  wire   v_250cc16c_4978_4198_9322_2e0131c0c3d0;
  assign v_250cc16c_4978_4198_9322_2e0131c0c3d0 = a[3] & b[4];
  wire   v_00062549_b06e_45f1_a63c_3d8c992bf9c3;
  assign v_00062549_b06e_45f1_a63c_3d8c992bf9c3 = a[3] & b[5];
  wire   e9682f56_852f_425c_8683_3ff46957042b;
  assign e9682f56_852f_425c_8683_3ff46957042b = a[3] & b[6];
  wire   v_3a806a8e_8dbd_4301_8aea_a61eeb37e120;
  assign v_3a806a8e_8dbd_4301_8aea_a61eeb37e120 = a[3] & b[7];
  wire   a2924871_dcd0_409d_aef2_e87a11ad4e47;
  assign a2924871_dcd0_409d_aef2_e87a11ad4e47 = a[4] & b[0];
  wire   v_33c751bf_56b8_415c_820e_924a090e9c12;
  assign v_33c751bf_56b8_415c_820e_924a090e9c12 = a[4] & b[1];
  wire   v_5d5f32d1_25e9_433a_9e19_ce3335da3a31;
  assign v_5d5f32d1_25e9_433a_9e19_ce3335da3a31 = a[4] & b[2];
  wire   v_80865785_14c6_4865_90fc_07bf8ae7618e;
  assign v_80865785_14c6_4865_90fc_07bf8ae7618e = a[4] & b[3];
  wire   v_08ca6fb1_ba3b_4f25_8bc1_811ca670992d;
  assign v_08ca6fb1_ba3b_4f25_8bc1_811ca670992d = a[4] & b[4];
  wire   v_6dcf50f8_eb1a_463d_a49c_4d7fae0e610c;
  assign v_6dcf50f8_eb1a_463d_a49c_4d7fae0e610c = a[4] & b[5];
  wire   v_712d102d_a1b5_4cd9_879e_ba3fbb92de62;
  assign v_712d102d_a1b5_4cd9_879e_ba3fbb92de62 = a[4] & b[6];
  wire   v_528c3819_4f30_4cf0_ac28_49f77c6b742b;
  assign v_528c3819_4f30_4cf0_ac28_49f77c6b742b = a[4] & b[7];
  wire   d6a47aad_a1d9_48e0_87a2_039bac0f757b;
  assign d6a47aad_a1d9_48e0_87a2_039bac0f757b = a[5] & b[0];
  wire   v_4592672a_9d2a_44a2_9f59_5da20d2953a7;
  assign v_4592672a_9d2a_44a2_9f59_5da20d2953a7 = a[5] & b[1];
  wire   e9bb6a78_43df_49d0_a782_b39eb8b65850;
  assign e9bb6a78_43df_49d0_a782_b39eb8b65850 = a[5] & b[2];
  wire   f57846db_942f_4569_b2f7_dfa9e77b5f49;
  assign f57846db_942f_4569_b2f7_dfa9e77b5f49 = a[5] & b[3];
  wire   f4ca1635_ebb7_48cb_a4b6_c2d34a744577;
  assign f4ca1635_ebb7_48cb_a4b6_c2d34a744577 = a[5] & b[4];
  wire   v_9cc236cf_efd8_4917_9538_cb44b7e9890d;
  assign v_9cc236cf_efd8_4917_9538_cb44b7e9890d = a[5] & b[5];
  wire   ec65d2f8_0336_4909_84e3_7dbb2940855c;
  assign ec65d2f8_0336_4909_84e3_7dbb2940855c = a[5] & b[6];
  wire   v_2d78d33a_0372_4685_970e_6fd32ac262bd;
  assign v_2d78d33a_0372_4685_970e_6fd32ac262bd = a[5] & b[7];
  wire   f1513491_7423_4a4a_8594_94644382e8bb;
  assign f1513491_7423_4a4a_8594_94644382e8bb = a[6] & b[0];
  wire   v_05a0a58e_be32_4294_8c74_65515c0490b6;
  assign v_05a0a58e_be32_4294_8c74_65515c0490b6 = a[6] & b[1];
  wire   a351ae23_e3ee_4aa8_ad9f_64bd7eec1f45;
  assign a351ae23_e3ee_4aa8_ad9f_64bd7eec1f45 = a[6] & b[2];
  wire   fd0728c3_5301_43c2_803d_c5bb393d456a;
  assign fd0728c3_5301_43c2_803d_c5bb393d456a = a[6] & b[3];
  wire   v_81988169_640b_41dc_b29c_e2460805caae;
  assign v_81988169_640b_41dc_b29c_e2460805caae = a[6] & b[4];
  wire   v_08108c7e_ac33_4a07_be68_d9e43638031c;
  assign v_08108c7e_ac33_4a07_be68_d9e43638031c = a[6] & b[5];
  wire   v_0c14468f_56a4_41eb_b012_4b65b693043e;
  assign v_0c14468f_56a4_41eb_b012_4b65b693043e = a[6] & b[6];
  wire   b8496108_90e9_4736_8cf7_47681a257947;
  assign b8496108_90e9_4736_8cf7_47681a257947 = a[6] & b[7];
  wire   e2d5f893_2154_44a7_885b_f047252e95cf;
  assign e2d5f893_2154_44a7_885b_f047252e95cf = a[7] & b[0];
  wire   v_10b0a20c_8bef_4cea_a2db_c43028ff33c4;
  assign v_10b0a20c_8bef_4cea_a2db_c43028ff33c4 = a[7] & b[1];
  wire   v_0edac932_8d85_4cfd_8d85_c90e6ae4c21d;
  assign v_0edac932_8d85_4cfd_8d85_c90e6ae4c21d = a[7] & b[2];
  wire   v_9b4b46df_6d2f_4167_a79a_ca73aaa0bff8;
  assign v_9b4b46df_6d2f_4167_a79a_ca73aaa0bff8 = a[7] & b[3];
  wire   a309729c_3f7b_4823_86f2_c76a6571b95b;
  assign a309729c_3f7b_4823_86f2_c76a6571b95b = a[7] & b[4];
  wire   v_09e1e636_5c9d_41f7_8f23_9e197edeb3e7;
  assign v_09e1e636_5c9d_41f7_8f23_9e197edeb3e7 = a[7] & b[5];
  wire   a9f57e75_c0cb_4b11_b082_3ed8445f3c7c;
  assign a9f57e75_c0cb_4b11_b082_3ed8445f3c7c = a[7] & b[6];
  wire   v_57213757_b647_4e5d_8d62_14d536832e08;
  assign v_57213757_b647_4e5d_8d62_14d536832e08 = a[7] & b[7];

  /*================================================================================*/

  wire   v_03811acc_b667_4e33_bbc6_38cc1a22432d;
  wire   v_97377eb8_2cf3_427b_ba1b_fc70ede7726d;
  assign {v_97377eb8_2cf3_427b_ba1b_fc70ede7726d, v_03811acc_b667_4e33_bbc6_38cc1a22432d} = v_6e8bd969_5a8c_4cfb_b27f_bc219fc2b830 + v_1d2ce400_bee3_4bcf_ad94_392b55ae8828;
  wire   v_2d630563_47a5_4b6d_8457_5de55f334d79;
  wire   v_7181854d_0fc7_425c_85c0_d35010a32f8c;
  assign {v_7181854d_0fc7_425c_85c0_d35010a32f8c, v_2d630563_47a5_4b6d_8457_5de55f334d79} = v_789d6bce_b7aa_43ae_b7b8_fbb08e0b9a35 + e3eceaf8_b4db_4924_b72f_73344f9788f2 + v_4e4a185f_ac21_47d0_b0b5_94dea7bf9f3e;
  wire   v_34a78f9a_2836_4f0d_a625_e0ec848a50b1;
  wire   v_5538a28c_aa08_4fc9_8053_5343bd9fcf2f;
  assign {v_5538a28c_aa08_4fc9_8053_5343bd9fcf2f, v_34a78f9a_2836_4f0d_a625_e0ec848a50b1} = v_250cc16c_4978_4198_9322_2e0131c0c3d0 + v_80865785_14c6_4865_90fc_07bf8ae7618e;
  wire   v_5b5395f2_0b26_46fe_bc94_7bcdac125a5e;
  wire   v_506869be_947b_4b1c_b829_5b0d1dc18cdf;
  assign {v_506869be_947b_4b1c_b829_5b0d1dc18cdf, v_5b5395f2_0b26_46fe_bc94_7bcdac125a5e} = v_100c1758_140a_4142_9a4d_4fed30a453c6 + f4fcffeb_a640_44c2_b3a1_45f75bc65452 + v_00062549_b06e_45f1_a63c_3d8c992bf9c3;
  wire   e28074da_7bae_4dfc_a60a_93f18848195f;
  wire   v_764c5c80_d24d_4c38_9871_ed9ae703cd11;
  assign {v_764c5c80_d24d_4c38_9871_ed9ae703cd11, e28074da_7bae_4dfc_a60a_93f18848195f} = v_08ca6fb1_ba3b_4f25_8bc1_811ca670992d + f57846db_942f_4569_b2f7_dfa9e77b5f49;
  wire   v_0576efc7_5c3e_42f9_9afa_321e1330e393;
  wire   c755c6d5_027e_41af_9029_7734571855fe;
  assign {c755c6d5_027e_41af_9029_7734571855fe, v_0576efc7_5c3e_42f9_9afa_321e1330e393} = v_8c4302bb_a1c1_446c_82b6_f699d6d7184f + e9682f56_852f_425c_8683_3ff46957042b + v_6dcf50f8_eb1a_463d_a49c_4d7fae0e610c;

  /*================================================================================*/

  wire   v_99a1dec2_988f_4ad8_a155_9db0410c26e2;
  wire   d1bd184e_6a26_4a62_b851_38f05c76bcef;
  assign {d1bd184e_6a26_4a62_b851_38f05c76bcef, v_99a1dec2_988f_4ad8_a155_9db0410c26e2} = v_348f0a68_d598_46cc_86ac_cf3917220f9c + v_61208a32_2b3a_47a2_a8e4_63e32df27f2e;
  wire   fbcea37c_7cb9_4c35_bf68_ee743badb84f;
  wire   v_7a2088a0_b6a5_4955_8ccc_09b6cb9ec5ec;
  assign {v_7a2088a0_b6a5_4955_8ccc_09b6cb9ec5ec, fbcea37c_7cb9_4c35_bf68_ee743badb84f} = v_2fe938e1_c440_40ee_956d_e2cf08b43207 + d0d5447b_4d96_4162_8631_3197aee6fbe5 + v_53863f08_0fcf_4548_bea8_65d01281c248;
  wire   v_1bc1bb5e_ee23_4470_bfb3_630acd97bbd1;
  wire   v_55ba2971_1d25_474f_bcef_320a713856d2;
  assign {v_55ba2971_1d25_474f_bcef_320a713856d2, v_1bc1bb5e_ee23_4470_bfb3_630acd97bbd1} = d3f8aa95_a395_4d1a_a4f7_6f39ea2b077b + v_33c751bf_56b8_415c_820e_924a090e9c12;
  wire   a616a033_9a05_4a43_b7e3_816411664fd6;
  wire   f07eccf1_7334_4192_9b0b_144a7e2f157c;
  assign {f07eccf1_7334_4192_9b0b_144a7e2f157c, a616a033_9a05_4a43_b7e3_816411664fd6} = fef89f08_5c22_497d_b9e9_75612421a902 + v_1b137b5f_c38c_471e_b330_09c52f7d7481 + v_5d5f32d1_25e9_433a_9e19_ce3335da3a31;
  wire   bf8c712a_f6ac_40f5_bb8f_69c8e65fcd3b;
  wire   ed517bc2_032b_4348_b836_6d20a64bc2ce;
  assign {ed517bc2_032b_4348_b836_6d20a64bc2ce, bf8c712a_f6ac_40f5_bb8f_69c8e65fcd3b} = v_4592672a_9d2a_44a2_9f59_5da20d2953a7 + f1513491_7423_4a4a_8594_94644382e8bb + v_03811acc_b667_4e33_bbc6_38cc1a22432d;
  wire   v_82367c68_d3bb_4ab5_97d4_998d372ec9eb;
  wire   cb8bc776_0b04_4436_b9b9_a90461edb551;
  assign {cb8bc776_0b04_4436_b9b9_a90461edb551, v_82367c68_d3bb_4ab5_97d4_998d372ec9eb} = e9bb6a78_43df_49d0_a782_b39eb8b65850 + v_05a0a58e_be32_4294_8c74_65515c0490b6 + e2d5f893_2154_44a7_885b_f047252e95cf;
  wire   v_36d78715_fd86_4620_88de_00d594446c6f;
  wire   v_5a6304bf_57c1_44f5_bb19_1b59056ff9c9;
  assign {v_5a6304bf_57c1_44f5_bb19_1b59056ff9c9, v_36d78715_fd86_4620_88de_00d594446c6f} = v_97377eb8_2cf3_427b_ba1b_fc70ede7726d + v_2d630563_47a5_4b6d_8457_5de55f334d79 + v_34a78f9a_2836_4f0d_a625_e0ec848a50b1;
  wire   de1da632_f8e5_42d8_944c_eefa36961572;
  wire   v_93dc911a_8d51_4931_ad66_e635fd760583;
  assign {v_93dc911a_8d51_4931_ad66_e635fd760583, de1da632_f8e5_42d8_944c_eefa36961572} = a351ae23_e3ee_4aa8_ad9f_64bd7eec1f45 + v_10b0a20c_8bef_4cea_a2db_c43028ff33c4 + v_7181854d_0fc7_425c_85c0_d35010a32f8c;
  wire   v_3f0e4a31_aaf2_4206_9674_be1bc917e5a4;
  wire   efc3aa22_c7ac_4d99_b800_ebefbe15a450;
  assign {efc3aa22_c7ac_4d99_b800_ebefbe15a450, v_3f0e4a31_aaf2_4206_9674_be1bc917e5a4} = v_5538a28c_aa08_4fc9_8053_5343bd9fcf2f + v_5b5395f2_0b26_46fe_bc94_7bcdac125a5e + e28074da_7bae_4dfc_a60a_93f18848195f;
  wire   v_91ab1346_420e_4841_9b4e_79267775159e;
  wire   v_31171b53_7bc8_45e7_ba81_f8ffe6902918;
  assign {v_31171b53_7bc8_45e7_ba81_f8ffe6902918, v_91ab1346_420e_4841_9b4e_79267775159e} = f4ca1635_ebb7_48cb_a4b6_c2d34a744577 + fd0728c3_5301_43c2_803d_c5bb393d456a + v_0edac932_8d85_4cfd_8d85_c90e6ae4c21d;
  wire   v_427edf83_2efa_4d6c_8d3d_01f50198bcda;
  wire   v_1fd39b45_b438_4774_8242_e6f6e2bc037d;
  assign {v_1fd39b45_b438_4774_8242_e6f6e2bc037d, v_427edf83_2efa_4d6c_8d3d_01f50198bcda} = v_506869be_947b_4b1c_b829_5b0d1dc18cdf + v_764c5c80_d24d_4c38_9871_ed9ae703cd11 + v_0576efc7_5c3e_42f9_9afa_321e1330e393;
  wire   v_2dfd07f2_4499_4ee5_9ecc_5467189fda91;
  wire   v_62013513_ea0d_4ef1_ab72_d21063e5f580;
  assign {v_62013513_ea0d_4ef1_ab72_d21063e5f580, v_2dfd07f2_4499_4ee5_9ecc_5467189fda91} = v_3a806a8e_8dbd_4301_8aea_a61eeb37e120 + v_712d102d_a1b5_4cd9_879e_ba3fbb92de62 + v_9cc236cf_efd8_4917_9538_cb44b7e9890d;
  wire   a238020a_f1f2_4275_8834_07c4dc8720c7;
  wire   bf7bc111_d777_4883_9a5d_51418645b348;
  assign {bf7bc111_d777_4883_9a5d_51418645b348, a238020a_f1f2_4275_8834_07c4dc8720c7} = v_81988169_640b_41dc_b29c_e2460805caae + v_9b4b46df_6d2f_4167_a79a_ca73aaa0bff8 + c755c6d5_027e_41af_9029_7734571855fe;
  wire   v_1240922f_741e_4f5d_ba43_bffbe61999d1;
  wire   a632085c_45c5_4cb2_8762_8475ec144f19;
  assign {a632085c_45c5_4cb2_8762_8475ec144f19, v_1240922f_741e_4f5d_ba43_bffbe61999d1} = v_528c3819_4f30_4cf0_ac28_49f77c6b742b + ec65d2f8_0336_4909_84e3_7dbb2940855c + v_08108c7e_ac33_4a07_be68_d9e43638031c;

  /*================================================================================*/

  wire   v_755d4173_47c3_455a_9916_db3ff646fbde;
  wire   c9376aef_0735_4bad_b1a3_10ad7313b5e4;
  assign {c9376aef_0735_4bad_b1a3_10ad7313b5e4, v_755d4173_47c3_455a_9916_db3ff646fbde} = cba0d86c_fd35_439e_ad86_15b52ad7b774 + fb76f062_83f0_48a9_8b48_c1ebd32e8c32;
  wire   v_4a004ca7_f4ac_40de_858e_9fa853b627ba;
  wire   v_193206c5_9138_44de_b490_30175b6b1029;
  assign {v_193206c5_9138_44de_b490_30175b6b1029, v_4a004ca7_f4ac_40de_858e_9fa853b627ba} = a62a3e4b_a0aa_45f3_8cf0_ac8d7d8e2177 + df8d13ca_4a65_43f9_96d9_ac6de1c0e237 + a2924871_dcd0_409d_aef2_e87a11ad4e47;
  wire   v_22cb2e99_9f99_4bd4_8416_d61db3e498be;
  wire   v_3a6cc5c5_2a82_48b0_986e_a183cbd92e98;
  assign {v_3a6cc5c5_2a82_48b0_986e_a183cbd92e98, v_22cb2e99_9f99_4bd4_8416_d61db3e498be} = d6a47aad_a1d9_48e0_87a2_039bac0f757b + d1bd184e_6a26_4a62_b851_38f05c76bcef + fbcea37c_7cb9_4c35_bf68_ee743badb84f;
  wire   v_975aeaf6_0055_464c_85fc_25005d4c7397;
  wire   cb6adc5a_7719_4bb7_aa9e_2c4a9c000c7f;
  assign {cb6adc5a_7719_4bb7_aa9e_2c4a9c000c7f, v_975aeaf6_0055_464c_85fc_25005d4c7397} = v_7a2088a0_b6a5_4955_8ccc_09b6cb9ec5ec + v_55ba2971_1d25_474f_bcef_320a713856d2 + a616a033_9a05_4a43_b7e3_816411664fd6;
  wire   v_488e941a_8650_4bd2_b56a_f17e853b27b9;
  wire   v_0b5aaf33_ee03_4371_9d28_576c0b56c51c;
  assign {v_0b5aaf33_ee03_4371_9d28_576c0b56c51c, v_488e941a_8650_4bd2_b56a_f17e853b27b9} = f07eccf1_7334_4192_9b0b_144a7e2f157c + ed517bc2_032b_4348_b836_6d20a64bc2ce + v_82367c68_d3bb_4ab5_97d4_998d372ec9eb;
  wire   e5527040_3f87_4e90_9914_c58231378bb3;
  wire   v_02ed7190_9acd_4337_a059_3b1bb113e97a;
  assign {v_02ed7190_9acd_4337_a059_3b1bb113e97a, e5527040_3f87_4e90_9914_c58231378bb3} = cb8bc776_0b04_4436_b9b9_a90461edb551 + v_5a6304bf_57c1_44f5_bb19_1b59056ff9c9 + de1da632_f8e5_42d8_944c_eefa36961572;
  wire   b3026287_7f3d_4e14_9cd3_8ec210a544d9;
  wire   v_0a9bcd4c_06fc_4144_b2cf_67953c777aea;
  assign {v_0a9bcd4c_06fc_4144_b2cf_67953c777aea, b3026287_7f3d_4e14_9cd3_8ec210a544d9} = v_93dc911a_8d51_4931_ad66_e635fd760583 + efc3aa22_c7ac_4d99_b800_ebefbe15a450 + v_91ab1346_420e_4841_9b4e_79267775159e;
  wire   b5825186_ed72_4f28_a8ef_2dfdad849ca2;
  wire   v_948d5d8e_12f9_4d9b_b7dd_dacc7c921d1d;
  assign {v_948d5d8e_12f9_4d9b_b7dd_dacc7c921d1d, b5825186_ed72_4f28_a8ef_2dfdad849ca2} = v_31171b53_7bc8_45e7_ba81_f8ffe6902918 + v_1fd39b45_b438_4774_8242_e6f6e2bc037d + v_2dfd07f2_4499_4ee5_9ecc_5467189fda91;
  wire   v_9cc3021b_301e_4221_869d_befd97d162d9;
  wire   f7879270_09d3_4b76_8289_bb82fcd8e99b;
  assign {f7879270_09d3_4b76_8289_bb82fcd8e99b, v_9cc3021b_301e_4221_869d_befd97d162d9} = a309729c_3f7b_4823_86f2_c76a6571b95b + v_62013513_ea0d_4ef1_ab72_d21063e5f580 + bf7bc111_d777_4883_9a5d_51418645b348;
  wire   dd7649f8_df12_4f5d_95a9_5fbde7473e73;
  wire   v_275a7616_9438_4e40_b934_131d7d4d5860;
  assign {v_275a7616_9438_4e40_b934_131d7d4d5860, dd7649f8_df12_4f5d_95a9_5fbde7473e73} = v_2d78d33a_0372_4685_970e_6fd32ac262bd + v_0c14468f_56a4_41eb_b012_4b65b693043e + v_09e1e636_5c9d_41f7_8f23_9e197edeb3e7;

  /*================================================================================*/

  wire   v_2402a8d6_f802_4698_854d_afe6aec1ed16;
  wire   v_014e0113_7af0_4ccf_a650_f0f282ecb77d;
  assign {v_014e0113_7af0_4ccf_a650_f0f282ecb77d, v_2402a8d6_f802_4698_854d_afe6aec1ed16} = v_3eef52ac_6195_4627_96b5_507e1b86bf39 + v_938c4adf_0c3c_47f3_909d_1735d843f860;
  wire   v_185a1587_da92_474a_a18f_1d8939f74182;
  wire   v_687112d4_63a7_455b_9073_e4d745e02078;
  assign {v_687112d4_63a7_455b_9073_e4d745e02078, v_185a1587_da92_474a_a18f_1d8939f74182} = v_568c08f8_3850_4cf1_81aa_8ad0e5e8a283 + a61f7549_5f9b_4cca_81f1_9dfeffa545cd + v_755d4173_47c3_455a_9916_db3ff646fbde;
  wire   ca21ddca_1369_487f_aed8_d083eb37e617;
  wire   v_35d910d1_f916_455f_abc1_c6d2a0df9e67;
  assign {v_35d910d1_f916_455f_abc1_c6d2a0df9e67, ca21ddca_1369_487f_aed8_d083eb37e617} = v_99a1dec2_988f_4ad8_a155_9db0410c26e2 + c9376aef_0735_4bad_b1a3_10ad7313b5e4 + v_4a004ca7_f4ac_40de_858e_9fa853b627ba;
  wire   v_430f33b1_2dbe_46b2_a91a_6ebe1a53803b;
  wire   v_0e61d1cd_a60e_4745_822c_57ea08e2b918;
  assign {v_0e61d1cd_a60e_4745_822c_57ea08e2b918, v_430f33b1_2dbe_46b2_a91a_6ebe1a53803b} = v_1bc1bb5e_ee23_4470_bfb3_630acd97bbd1 + v_193206c5_9138_44de_b490_30175b6b1029 + v_22cb2e99_9f99_4bd4_8416_d61db3e498be;
  wire   v_8367db16_c7b4_4168_aa7b_2160d38e5ed4;
  wire   v_53fecdea_f7e4_4e8f_ac8d_8782c6766b6a;
  assign {v_53fecdea_f7e4_4e8f_ac8d_8782c6766b6a, v_8367db16_c7b4_4168_aa7b_2160d38e5ed4} = bf8c712a_f6ac_40f5_bb8f_69c8e65fcd3b + v_3a6cc5c5_2a82_48b0_986e_a183cbd92e98 + v_975aeaf6_0055_464c_85fc_25005d4c7397;
  wire   a8146aeb_5f0b_487e_a181_a82c685ab516;
  wire   v_1305c6cf_5602_4c0b_8cb8_ea42297c1bea;
  assign {v_1305c6cf_5602_4c0b_8cb8_ea42297c1bea, a8146aeb_5f0b_487e_a181_a82c685ab516} = v_36d78715_fd86_4620_88de_00d594446c6f + cb6adc5a_7719_4bb7_aa9e_2c4a9c000c7f + v_488e941a_8650_4bd2_b56a_f17e853b27b9;
  wire   v_4598845b_d2a3_4b33_8cb2_d3038360198f;
  wire   v_7858a1ae_857b_442f_8cc7_af137dc3adf9;
  assign {v_7858a1ae_857b_442f_8cc7_af137dc3adf9, v_4598845b_d2a3_4b33_8cb2_d3038360198f} = v_3f0e4a31_aaf2_4206_9674_be1bc917e5a4 + v_0b5aaf33_ee03_4371_9d28_576c0b56c51c + e5527040_3f87_4e90_9914_c58231378bb3;
  wire   a48d4d38_42fc_4370_b79c_835fc07da028;
  wire   v_829b6203_3a61_4c09_932e_35ddce27a600;
  assign {v_829b6203_3a61_4c09_932e_35ddce27a600, a48d4d38_42fc_4370_b79c_835fc07da028} = v_427edf83_2efa_4d6c_8d3d_01f50198bcda + v_02ed7190_9acd_4337_a059_3b1bb113e97a + b3026287_7f3d_4e14_9cd3_8ec210a544d9;
  wire   v_55cef5be_ee98_463b_a486_dc5dd0a4f531;
  wire   ebcbea95_c563_431f_9c77_aa96975fb599;
  assign {ebcbea95_c563_431f_9c77_aa96975fb599, v_55cef5be_ee98_463b_a486_dc5dd0a4f531} = a238020a_f1f2_4275_8834_07c4dc8720c7 + v_0a9bcd4c_06fc_4144_b2cf_67953c777aea + b5825186_ed72_4f28_a8ef_2dfdad849ca2;
  wire   e53ce623_26f8_4a26_9239_3299754a220f;
  wire   v_51f74141_c5b5_4292_81fc_1a19f334ca32;
  assign {v_51f74141_c5b5_4292_81fc_1a19f334ca32, e53ce623_26f8_4a26_9239_3299754a220f} = v_1240922f_741e_4f5d_ba43_bffbe61999d1 + v_948d5d8e_12f9_4d9b_b7dd_dacc7c921d1d + v_9cc3021b_301e_4221_869d_befd97d162d9;
  wire   d39e7260_eab2_41c9_948f_8cf1c810d1c3;
  wire   v_1d5fe3b0_3453_414c_86ff_94342aec79f7;
  assign {v_1d5fe3b0_3453_414c_86ff_94342aec79f7, d39e7260_eab2_41c9_948f_8cf1c810d1c3} = a632085c_45c5_4cb2_8762_8475ec144f19 + f7879270_09d3_4b76_8289_bb82fcd8e99b + dd7649f8_df12_4f5d_95a9_5fbde7473e73;
  wire   f54bd499_505e_40ab_ac9b_4576b6460b08;
  wire   v_0ef9621f_2c38_455f_a217_420c4c346371;
  assign {v_0ef9621f_2c38_455f_a217_420c4c346371, f54bd499_505e_40ab_ac9b_4576b6460b08} = b8496108_90e9_4736_8cf7_47681a257947 + a9f57e75_c0cb_4b11_b082_3ed8445f3c7c + v_275a7616_9438_4e40_b934_131d7d4d5860;

  /*================================================================================*/

  assign product = {v_57213757_b647_4e5d_8d62_14d536832e08, v_1d5fe3b0_3453_414c_86ff_94342aec79f7, v_51f74141_c5b5_4292_81fc_1a19f334ca32, ebcbea95_c563_431f_9c77_aa96975fb599, v_829b6203_3a61_4c09_932e_35ddce27a600, v_7858a1ae_857b_442f_8cc7_af137dc3adf9, v_1305c6cf_5602_4c0b_8cb8_ea42297c1bea, v_53fecdea_f7e4_4e8f_ac8d_8782c6766b6a, v_0e61d1cd_a60e_4745_822c_57ea08e2b918, v_35d910d1_f916_455f_abc1_c6d2a0df9e67, v_687112d4_63a7_455b_9073_e4d745e02078, v_014e0113_7af0_4ccf_a650_f0f282ecb77d, v_259bb6be_d84f_49d7_87e9_795706241c88, f95f8062_3816_42ce_9a01_453aa82aa344, c5b87c13_749f_4d1b_8646_4ab3378e8a5a} + {v_0ef9621f_2c38_455f_a217_420c4c346371, f54bd499_505e_40ab_ac9b_4576b6460b08, d39e7260_eab2_41c9_948f_8cf1c810d1c3, e53ce623_26f8_4a26_9239_3299754a220f, v_55cef5be_ee98_463b_a486_dc5dd0a4f531, a48d4d38_42fc_4370_b79c_835fc07da028, v_4598845b_d2a3_4b33_8cb2_d3038360198f, a8146aeb_5f0b_487e_a181_a82c685ab516, v_8367db16_c7b4_4168_aa7b_2160d38e5ed4, v_430f33b1_2dbe_46b2_a91a_6ebe1a53803b, ca21ddca_1369_487f_aed8_d083eb37e617, v_185a1587_da92_474a_a18f_1d8939f74182, v_2402a8d6_f802_4698_854d_afe6aec1ed16, c8e02cbd_eca3_4c29_860b_7e21223bbb82, 1'b0};

  /*================================================================================*/


endmodule
